version: 2
jobs:
    build:
        working_directory: /rapidpro/
        docker:
            -   image: praekeltfoundation/rapidpro:v3
                environment:
                    PIP_EXTRA_INDEX_URL: https://jessie.wheelhouse.praekelt.org/simple/
                    DATABASE_URL: postgis://rapidpro:rapidpro@localhost/rapidpro
                    EXTRA_INSTALLED_APPS: warapidpro
                    SECRET_KEY: 'really-quite-obvious'
            -   image: mdillon/postgis:9.4
                environment:
                    POSTGRES_USER: rapidpro
                    POSTGRES_DB: rapidpro
                    POSTGRES_PASSWORD: rapidpro
        steps:
            -   checkout
            -   run:
                    name: "Run RapidPro checks"
                    command: |
                        /venv/bin/python /rapidpro/manage.py test warapidpro -v3
