version: 2
jobs:
    build:
        working_directory: /rapidpro/warapidpro
        docker:
            -   image: praekeltfoundation/rapidpro:v3.0.136p18
                environment:
                    PIP_EXTRA_INDEX_URL: https://jessie.wheelhouse.praekelt.org/simple/
                    DATABASE_URL: postgis://rapidpro:rapidpro@localhost/rapidpro
                    REDIS_URL: redis://localhost:6379/0
                    EXTRA_INSTALLED_APPS: warapidpro
                    RAPIDPRO_VERSION: 3
                    SECRET_KEY: 'really-quite-obvious'
            -   image: circleci/postgres:9.4-alpine-postgis
                environment:
                    POSTGRES_USER: rapidpro
                    POSTGRES_DB: rapidpro
                    POSTGRES_PASSWORD: rapidpro
            -   image: redis
        steps:
            -   checkout
            -   run:
                    name: "Run RapidPro checks"
                    command: |
                        # Give mdillon/postgis some time to get its act together
                        sleep 20
                        /venv/bin/pip install -e /rapidpro/warapidpro/
                        /venv/bin/python /rapidpro/manage.py test warapidpro -v2
            -   run:
                    name: "Auto deploy"
                    when: on_success
                    command: |
                        apk update
                        apk add git
                        cd /rapidpro/warapidpro
                        VERSION=$(git describe --always)
                        if git describe | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$";
                        then
                            # build package and upload to private pypi index
                            echo "[distutils]" >> ~/.pypirc
                            echo "index-servers = pypi" >> ~/.pypirc
                            echo "[pypi]" >> ~/.pypirc
                            echo "username=$PYPI_USERNAME" >> ~/.pypirc
                            echo "password=$PYPI_PASSWORD" >> ~/.pypirc
                            python setup.py sdist bdist_wheel
                            /venv/bin/pip install twine
                            /venv/bin/twine upload --skip-existing dist/*
                        fi
    release:
        working_directory: ~/app
        docker:
            -   image: docker:latest
        steps:
            -   checkout
            -   setup_remote_docker
            -   run:
                    name: Build application Docker image
                    command: |
                        cd docker
                        docker login --username praekeltorgdeploy --password $PRAEKELTORGDEPLOY_PASSWORD
                        docker build -t praekeltfoundation/rapidpro-engage:latest .
                        docker push praekeltfoundation/rapidpro-engage:latest

                        # If this is a version then tag and push that too.
                        if git describe | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$"
                        then
                            VERSION=$(git describe)
                            docker tag praekeltfoundation/rapidpro-engage:latest praekeltfoundation/rapidpro-engage:latest:$VERSION
                            docker push praekeltfoundation/rapidpro-engage:$VERSION
                        fi

workflows:
    version: 2
    build_and_release:
        jobs:
            - build
            - release:
                # filters:
                #     branches:
                #         only:
                #             - develop
                requires:
                    - build
