version: 2
jobs:
    build:
        working_directory: /rapidpro/warapidpro
        docker:
            -   image: praekeltfoundation/rapidpro:v3
                environment:
                    PIP_EXTRA_INDEX_URL: https://jessie.wheelhouse.praekelt.org/simple/
                    DATABASE_URL: postgis://rapidpro:rapidpro@localhost/rapidpro
                    REDIS_URL: redis://localhost:6379/0
                    EXTRA_INSTALLED_APPS: warapidpro
                    RAPIDPRO_VERSION: 3
                    SECRET_KEY: 'really-quite-obvious'
            -   image: circleci/postgres:9.4-postgis
                environment:
                    POSTGRES_USER: rapidpro
                    POSTGRES_DB: rapidpro
                    POSTGRES_PASSWORD: rapidpro
            -   image: redis
        steps:
            -   checkout
            -   run:
                    name: "Run RapidPro checks"
                    command: |
                        /venv/bin/python /rapidpro/manage.py test warapidpro -v3
